name: CI

run-name: ${{ github.actor }} is update repo, start building...

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  # 允许您从“操作”选项卡手动运行此工作流
  workflow_dispatch:
# 设置权限（文件是可以被读写修改的）
permissions:
  contents: write
  pages: write
  id-token: write
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: Build
      run: |
        npm install
        npm run build
    - name: Commit and push
      run: |
        git add dist/*
        git commit -m "Deploy build artifact"
        git push origin master
    - name: Upload build artifacts
      uses: actions/upload-pages-artifact@v2
      with:
        path: dist
        name: build-output
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: publish
      uses: JamesIves/github-pages-deploy-action@4.1.4
      # uses: peaceiris/actions-gh-pages@v3
      # uses: actions/deploy-pages@v2
      with:
        branch: master
        folder: dist
        github_token: ${{ secrets.ACCESS_TOKEN }}
        # publish_dir: dist
        # force_orphan: true